package replay

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/bojieli/OpenRealtime/internal/audio"
	openaiwire "github.com/bojieli/OpenRealtime/protocol/openai"
	"github.com/bojieli/OpenRealtime/trace"
)

func TestReplayMatchesGoldenProtocolAndTrace(t *testing.T) {
	t.Parallel()
	repositoryRoot := filepath.Clean("..")
	fixture := filepath.Join(repositoryRoot, "tests", "fixtures", "m0-tone.wav")
	var events, traces bytes.Buffer
	summary, err := WAV(fixture, Options{
		SessionID: "m0-replay", FrameDurationMS: 20, Events: &events, Trace: &traces,
	})
	if err != nil {
		t.Fatal(err)
	}
	if summary.EventCount != 51 || summary.InputFrameCount != 50 ||
		summary.InputSampleCount != 24_000 || summary.DurationNS != 1_000_000_000 {
		t.Fatalf("unexpected summary: %+v", summary)
	}
	assertFileBytes(t, filepath.Join(repositoryRoot, "tests", "golden", "m0-openai-events.jsonl"), events.Bytes())
	assertFileBytes(t, filepath.Join(repositoryRoot, "tests", "golden", "m0-trace.jsonl"), traces.Bytes())
	validator := openaiwire.NewValidator()
	count, err := trace.Read(bytes.NewReader(traces.Bytes()), func(record trace.Record) error {
		message, err := openaiwire.Decode(record.Message)
		if err != nil {
			return err
		}
		return validator.Validate(record.Profile, record.Direction, message)
	})
	if err != nil || count != 51 {
		t.Fatalf("trace validation = (%d, %v), want (51, nil)", count, err)
	}
}

func TestReplayAbsoluteSampleTimingHasNoDrift(t *testing.T) {
	t.Parallel()
	fixture := filepath.Join(t.TempDir(), "fixture.wav")
	if _, err := audio.GenerateFixture(fixture); err != nil {
		t.Fatal(err)
	}
	var events, traces bytes.Buffer
	summary, err := WAV(fixture, Options{
		SessionID: "odd-cadence", FrameDurationMS: 17, Events: &events, Trace: &traces,
	})
	if err != nil {
		t.Fatal(err)
	}
	if summary.DurationNS != 1_000_000_000 || summary.InputSampleCount != 24_000 {
		t.Fatalf("unexpected summary: %+v", summary)
	}
	var final uint64
	if _, err := trace.Read(bytes.NewReader(traces.Bytes()), func(record trace.Record) error {
		final = record.MonotonicNS
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	if final != 1_000_000_000 {
		t.Fatalf("final monotonic_ns = %d, want 1000000000", final)
	}
}

func assertFileBytes(t *testing.T, path string, got []byte) {
	t.Helper()
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("generated bytes differ from %s", path)
	}
}
