// Code generated by cmd/specsync; DO NOT EDIT.
// Source: https://github.com/openai/openai-openapi/blob/2186421dca0cca7c1e67caa7739005e8b1ccc4dd/openapi.json at 2186421dca0cca7c1e67caa7739005e8b1ccc4dd (sha256:542299d304cdeb78deff4172b3790d52c7e7e75fb2b517e9c2787c52f1424acc), retrieved 2026-08-17.

package openai

const (
	EventConversationCreated                              EventType = "conversation.created"
	EventConversationItemAdded                            EventType = "conversation.item.added"
	EventConversationItemCreate                           EventType = "conversation.item.create"
	EventConversationItemCreated                          EventType = "conversation.item.created"
	EventConversationItemDelete                           EventType = "conversation.item.delete"
	EventConversationItemDeleted                          EventType = "conversation.item.deleted"
	EventConversationItemDone                             EventType = "conversation.item.done"
	EventConversationItemInputAudioTranscriptionCompleted EventType = "conversation.item.input_audio_transcription.completed"
	EventConversationItemInputAudioTranscriptionDelta     EventType = "conversation.item.input_audio_transcription.delta"
	EventConversationItemInputAudioTranscriptionFailed    EventType = "conversation.item.input_audio_transcription.failed"
	EventConversationItemInputAudioTranscriptionSegment   EventType = "conversation.item.input_audio_transcription.segment"
	EventConversationItemRetrieve                         EventType = "conversation.item.retrieve"
	EventConversationItemRetrieved                        EventType = "conversation.item.retrieved"
	EventConversationItemTruncate                         EventType = "conversation.item.truncate"
	EventConversationItemTruncated                        EventType = "conversation.item.truncated"
	EventError                                            EventType = "error"
	EventInputAudioBufferAppend                           EventType = "input_audio_buffer.append"
	EventInputAudioBufferClear                            EventType = "input_audio_buffer.clear"
	EventInputAudioBufferCleared                          EventType = "input_audio_buffer.cleared"
	EventInputAudioBufferCommit                           EventType = "input_audio_buffer.commit"
	EventInputAudioBufferCommitted                        EventType = "input_audio_buffer.committed"
	EventInputAudioBufferDtmfEventReceived                EventType = "input_audio_buffer.dtmf_event_received"
	EventInputAudioBufferSpeechStarted                    EventType = "input_audio_buffer.speech_started"
	EventInputAudioBufferSpeechStopped                    EventType = "input_audio_buffer.speech_stopped"
	EventInputAudioBufferTimeoutTriggered                 EventType = "input_audio_buffer.timeout_triggered"
	EventMcpListToolsCompleted                            EventType = "mcp_list_tools.completed"
	EventMcpListToolsFailed                               EventType = "mcp_list_tools.failed"
	EventMcpListToolsInProgress                           EventType = "mcp_list_tools.in_progress"
	EventOutputAudioBufferClear                           EventType = "output_audio_buffer.clear"
	EventOutputAudioBufferCleared                         EventType = "output_audio_buffer.cleared"
	EventOutputAudioBufferStarted                         EventType = "output_audio_buffer.started"
	EventOutputAudioBufferStopped                         EventType = "output_audio_buffer.stopped"
	EventRateLimitsUpdated                                EventType = "rate_limits.updated"
	EventResponseCancel                                   EventType = "response.cancel"
	EventResponseContentPartAdded                         EventType = "response.content_part.added"
	EventResponseContentPartDone                          EventType = "response.content_part.done"
	EventResponseCreate                                   EventType = "response.create"
	EventResponseCreated                                  EventType = "response.created"
	EventResponseDone                                     EventType = "response.done"
	EventResponseFunctionCallArgumentsDelta               EventType = "response.function_call_arguments.delta"
	EventResponseFunctionCallArgumentsDone                EventType = "response.function_call_arguments.done"
	EventResponseMcpCallCompleted                         EventType = "response.mcp_call.completed"
	EventResponseMcpCallFailed                            EventType = "response.mcp_call.failed"
	EventResponseMcpCallInProgress                        EventType = "response.mcp_call.in_progress"
	EventResponseMcpCallArgumentsDelta                    EventType = "response.mcp_call_arguments.delta"
	EventResponseMcpCallArgumentsDone                     EventType = "response.mcp_call_arguments.done"
	EventResponseOutputAudioDelta                         EventType = "response.output_audio.delta"
	EventResponseOutputAudioDone                          EventType = "response.output_audio.done"
	EventResponseOutputAudioTranscriptDelta               EventType = "response.output_audio_transcript.delta"
	EventResponseOutputAudioTranscriptDone                EventType = "response.output_audio_transcript.done"
	EventResponseOutputItemAdded                          EventType = "response.output_item.added"
	EventResponseOutputItemDone                           EventType = "response.output_item.done"
	EventResponseOutputTextDelta                          EventType = "response.output_text.delta"
	EventResponseOutputTextDone                           EventType = "response.output_text.done"
	EventSessionClose                                     EventType = "session.close"
	EventSessionClosed                                    EventType = "session.closed"
	EventSessionCreated                                   EventType = "session.created"
	EventSessionInputAudioBufferAppend                    EventType = "session.input_audio_buffer.append"
	EventSessionInputTranscriptDelta                      EventType = "session.input_transcript.delta"
	EventSessionOutputAudioDelta                          EventType = "session.output_audio.delta"
	EventSessionOutputTranscriptDelta                     EventType = "session.output_transcript.delta"
	EventSessionUpdate                                    EventType = "session.update"
	EventSessionUpdated                                   EventType = "session.updated"
	EventTranscriptionSessionCreated                      EventType = "transcription_session.created"
	EventTranscriptionSessionUpdate                       EventType = "transcription_session.update"
	EventTranscriptionSessionUpdated                      EventType = "transcription_session.updated"
)

var generatedDefinitions = []Definition{
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("conversation.item.create"), SchemaRef: "#/$defs/RealtimeBetaClientEventConversationItemCreate"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("conversation.item.delete"), SchemaRef: "#/$defs/RealtimeBetaClientEventConversationItemDelete"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("conversation.item.retrieve"), SchemaRef: "#/$defs/RealtimeBetaClientEventConversationItemRetrieve"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("conversation.item.truncate"), SchemaRef: "#/$defs/RealtimeBetaClientEventConversationItemTruncate"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("input_audio_buffer.append"), SchemaRef: "#/$defs/RealtimeBetaClientEventInputAudioBufferAppend"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("input_audio_buffer.clear"), SchemaRef: "#/$defs/RealtimeBetaClientEventInputAudioBufferClear"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("input_audio_buffer.commit"), SchemaRef: "#/$defs/RealtimeBetaClientEventInputAudioBufferCommit"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("output_audio_buffer.clear"), SchemaRef: "#/$defs/RealtimeBetaClientEventOutputAudioBufferClear"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("response.cancel"), SchemaRef: "#/$defs/RealtimeBetaClientEventResponseCancel"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("response.create"), SchemaRef: "#/$defs/RealtimeBetaClientEventResponseCreate"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("session.update"), SchemaRef: "#/$defs/RealtimeBetaClientEventSessionUpdate"},
	{Profile: Profile("beta"), Direction: Direction("client"), Type: EventType("transcription_session.update"), SchemaRef: "#/$defs/RealtimeBetaClientEventTranscriptionSessionUpdate"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("conversation.item.created"), SchemaRef: "#/$defs/RealtimeBetaServerEventConversationItemCreated"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("conversation.item.deleted"), SchemaRef: "#/$defs/RealtimeBetaServerEventConversationItemDeleted"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.completed"), SchemaRef: "#/$defs/RealtimeBetaServerEventConversationItemInputAudioTranscriptionCompleted"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.delta"), SchemaRef: "#/$defs/RealtimeBetaServerEventConversationItemInputAudioTranscriptionDelta"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.failed"), SchemaRef: "#/$defs/RealtimeBetaServerEventConversationItemInputAudioTranscriptionFailed"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.segment"), SchemaRef: "#/$defs/RealtimeBetaServerEventConversationItemInputAudioTranscriptionSegment"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("conversation.item.retrieved"), SchemaRef: "#/$defs/RealtimeBetaServerEventConversationItemRetrieved"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("conversation.item.truncated"), SchemaRef: "#/$defs/RealtimeBetaServerEventConversationItemTruncated"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("error"), SchemaRef: "#/$defs/RealtimeBetaServerEventError"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("input_audio_buffer.cleared"), SchemaRef: "#/$defs/RealtimeBetaServerEventInputAudioBufferCleared"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("input_audio_buffer.committed"), SchemaRef: "#/$defs/RealtimeBetaServerEventInputAudioBufferCommitted"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("input_audio_buffer.speech_started"), SchemaRef: "#/$defs/RealtimeBetaServerEventInputAudioBufferSpeechStarted"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("input_audio_buffer.speech_stopped"), SchemaRef: "#/$defs/RealtimeBetaServerEventInputAudioBufferSpeechStopped"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("mcp_list_tools.completed"), SchemaRef: "#/$defs/RealtimeBetaServerEventMCPListToolsCompleted"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("mcp_list_tools.failed"), SchemaRef: "#/$defs/RealtimeBetaServerEventMCPListToolsFailed"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("mcp_list_tools.in_progress"), SchemaRef: "#/$defs/RealtimeBetaServerEventMCPListToolsInProgress"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("rate_limits.updated"), SchemaRef: "#/$defs/RealtimeBetaServerEventRateLimitsUpdated"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.content_part.added"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseContentPartAdded"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.content_part.done"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseContentPartDone"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.created"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseCreated"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.done"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseDone"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.function_call_arguments.delta"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseFunctionCallArgumentsDelta"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.function_call_arguments.done"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseFunctionCallArgumentsDone"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.mcp_call.completed"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseMCPCallCompleted"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.mcp_call.failed"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseMCPCallFailed"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.mcp_call.in_progress"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseMCPCallInProgress"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.mcp_call_arguments.delta"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseMCPCallArgumentsDelta"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.mcp_call_arguments.done"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseMCPCallArgumentsDone"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.output_audio.delta"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseAudioDelta"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.output_audio.done"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseAudioDone"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.output_audio_transcript.delta"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseAudioTranscriptDelta"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.output_audio_transcript.done"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseAudioTranscriptDone"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.output_item.added"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseOutputItemAdded"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.output_item.done"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseOutputItemDone"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.output_text.delta"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseTextDelta"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("response.output_text.done"), SchemaRef: "#/$defs/RealtimeBetaServerEventResponseTextDone"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("session.created"), SchemaRef: "#/$defs/RealtimeBetaServerEventSessionCreated"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("session.updated"), SchemaRef: "#/$defs/RealtimeBetaServerEventSessionUpdated"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("transcription_session.created"), SchemaRef: "#/$defs/RealtimeBetaServerEventTranscriptionSessionCreated"},
	{Profile: Profile("beta"), Direction: Direction("server"), Type: EventType("transcription_session.updated"), SchemaRef: "#/$defs/RealtimeBetaServerEventTranscriptionSessionUpdated"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("conversation.item.create"), SchemaRef: "#/$defs/RealtimeClientEventConversationItemCreate"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("conversation.item.delete"), SchemaRef: "#/$defs/RealtimeClientEventConversationItemDelete"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("conversation.item.retrieve"), SchemaRef: "#/$defs/RealtimeClientEventConversationItemRetrieve"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("conversation.item.truncate"), SchemaRef: "#/$defs/RealtimeClientEventConversationItemTruncate"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("input_audio_buffer.append"), SchemaRef: "#/$defs/RealtimeClientEventInputAudioBufferAppend"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("input_audio_buffer.clear"), SchemaRef: "#/$defs/RealtimeClientEventInputAudioBufferClear"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("input_audio_buffer.commit"), SchemaRef: "#/$defs/RealtimeClientEventInputAudioBufferCommit"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("output_audio_buffer.clear"), SchemaRef: "#/$defs/RealtimeClientEventOutputAudioBufferClear"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("response.cancel"), SchemaRef: "#/$defs/RealtimeClientEventResponseCancel"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("response.create"), SchemaRef: "#/$defs/RealtimeClientEventResponseCreate"},
	{Profile: Profile("realtime"), Direction: Direction("client"), Type: EventType("session.update"), SchemaRef: "#/$defs/RealtimeClientEventSessionUpdate"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.created"), SchemaRef: "#/$defs/RealtimeServerEventConversationCreated"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.added"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemAdded"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.created"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemCreated"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.deleted"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemDeleted"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.done"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.completed"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemInputAudioTranscriptionCompleted"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.delta"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemInputAudioTranscriptionDelta"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.failed"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemInputAudioTranscriptionFailed"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.segment"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemInputAudioTranscriptionSegment"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.retrieved"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemRetrieved"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("conversation.item.truncated"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemTruncated"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("error"), SchemaRef: "#/$defs/RealtimeServerEventError"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("input_audio_buffer.cleared"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferCleared"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("input_audio_buffer.committed"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferCommitted"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("input_audio_buffer.dtmf_event_received"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferDtmfEventReceived"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("input_audio_buffer.speech_started"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferSpeechStarted"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("input_audio_buffer.speech_stopped"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferSpeechStopped"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("input_audio_buffer.timeout_triggered"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferTimeoutTriggered"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("mcp_list_tools.completed"), SchemaRef: "#/$defs/RealtimeServerEventMCPListToolsCompleted"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("mcp_list_tools.failed"), SchemaRef: "#/$defs/RealtimeServerEventMCPListToolsFailed"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("mcp_list_tools.in_progress"), SchemaRef: "#/$defs/RealtimeServerEventMCPListToolsInProgress"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("output_audio_buffer.cleared"), SchemaRef: "#/$defs/RealtimeServerEventOutputAudioBufferCleared"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("output_audio_buffer.started"), SchemaRef: "#/$defs/RealtimeServerEventOutputAudioBufferStarted"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("output_audio_buffer.stopped"), SchemaRef: "#/$defs/RealtimeServerEventOutputAudioBufferStopped"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("rate_limits.updated"), SchemaRef: "#/$defs/RealtimeServerEventRateLimitsUpdated"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.content_part.added"), SchemaRef: "#/$defs/RealtimeServerEventResponseContentPartAdded"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.content_part.done"), SchemaRef: "#/$defs/RealtimeServerEventResponseContentPartDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.created"), SchemaRef: "#/$defs/RealtimeServerEventResponseCreated"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.done"), SchemaRef: "#/$defs/RealtimeServerEventResponseDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.function_call_arguments.delta"), SchemaRef: "#/$defs/RealtimeServerEventResponseFunctionCallArgumentsDelta"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.function_call_arguments.done"), SchemaRef: "#/$defs/RealtimeServerEventResponseFunctionCallArgumentsDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.mcp_call.completed"), SchemaRef: "#/$defs/RealtimeServerEventResponseMCPCallCompleted"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.mcp_call.failed"), SchemaRef: "#/$defs/RealtimeServerEventResponseMCPCallFailed"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.mcp_call.in_progress"), SchemaRef: "#/$defs/RealtimeServerEventResponseMCPCallInProgress"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.mcp_call_arguments.delta"), SchemaRef: "#/$defs/RealtimeServerEventResponseMCPCallArgumentsDelta"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.mcp_call_arguments.done"), SchemaRef: "#/$defs/RealtimeServerEventResponseMCPCallArgumentsDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.output_audio.delta"), SchemaRef: "#/$defs/RealtimeServerEventResponseAudioDelta"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.output_audio.done"), SchemaRef: "#/$defs/RealtimeServerEventResponseAudioDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.output_audio_transcript.delta"), SchemaRef: "#/$defs/RealtimeServerEventResponseAudioTranscriptDelta"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.output_audio_transcript.done"), SchemaRef: "#/$defs/RealtimeServerEventResponseAudioTranscriptDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.output_item.added"), SchemaRef: "#/$defs/RealtimeServerEventResponseOutputItemAdded"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.output_item.done"), SchemaRef: "#/$defs/RealtimeServerEventResponseOutputItemDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.output_text.delta"), SchemaRef: "#/$defs/RealtimeServerEventResponseTextDelta"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("response.output_text.done"), SchemaRef: "#/$defs/RealtimeServerEventResponseTextDone"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("session.created"), SchemaRef: "#/$defs/RealtimeServerEventSessionCreated"},
	{Profile: Profile("realtime"), Direction: Direction("server"), Type: EventType("session.updated"), SchemaRef: "#/$defs/RealtimeServerEventSessionUpdated"},
	{Profile: Profile("transcription"), Direction: Direction("client"), Type: EventType("input_audio_buffer.append"), SchemaRef: "#/$defs/RealtimeClientEventInputAudioBufferAppend"},
	{Profile: Profile("transcription"), Direction: Direction("client"), Type: EventType("input_audio_buffer.clear"), SchemaRef: "#/$defs/RealtimeClientEventInputAudioBufferClear"},
	{Profile: Profile("transcription"), Direction: Direction("client"), Type: EventType("input_audio_buffer.commit"), SchemaRef: "#/$defs/RealtimeClientEventInputAudioBufferCommit"},
	{Profile: Profile("transcription"), Direction: Direction("client"), Type: EventType("transcription_session.update"), SchemaRef: "#/$defs/RealtimeClientEventTranscriptionSessionUpdate"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.completed"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemInputAudioTranscriptionCompleted"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.delta"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemInputAudioTranscriptionDelta"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.failed"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemInputAudioTranscriptionFailed"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("conversation.item.input_audio_transcription.segment"), SchemaRef: "#/$defs/RealtimeServerEventConversationItemInputAudioTranscriptionSegment"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("error"), SchemaRef: "#/$defs/RealtimeServerEventError"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("input_audio_buffer.cleared"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferCleared"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("input_audio_buffer.committed"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferCommitted"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("input_audio_buffer.speech_started"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferSpeechStarted"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("input_audio_buffer.speech_stopped"), SchemaRef: "#/$defs/RealtimeServerEventInputAudioBufferSpeechStopped"},
	{Profile: Profile("transcription"), Direction: Direction("server"), Type: EventType("transcription_session.updated"), SchemaRef: "#/$defs/RealtimeServerEventTranscriptionSessionUpdated"},
	{Profile: Profile("translation"), Direction: Direction("client"), Type: EventType("session.close"), SchemaRef: "#/$defs/RealtimeTranslationClientEventSessionClose"},
	{Profile: Profile("translation"), Direction: Direction("client"), Type: EventType("session.input_audio_buffer.append"), SchemaRef: "#/$defs/RealtimeTranslationClientEventInputAudioBufferAppend"},
	{Profile: Profile("translation"), Direction: Direction("client"), Type: EventType("session.update"), SchemaRef: "#/$defs/RealtimeTranslationClientEventSessionUpdate"},
	{Profile: Profile("translation"), Direction: Direction("server"), Type: EventType("error"), SchemaRef: "#/$defs/RealtimeServerEventError"},
	{Profile: Profile("translation"), Direction: Direction("server"), Type: EventType("session.closed"), SchemaRef: "#/$defs/RealtimeTranslationServerEventSessionClosed"},
	{Profile: Profile("translation"), Direction: Direction("server"), Type: EventType("session.created"), SchemaRef: "#/$defs/RealtimeTranslationServerEventSessionCreated"},
	{Profile: Profile("translation"), Direction: Direction("server"), Type: EventType("session.input_transcript.delta"), SchemaRef: "#/$defs/RealtimeTranslationServerEventSessionInputTranscriptDelta"},
	{Profile: Profile("translation"), Direction: Direction("server"), Type: EventType("session.output_audio.delta"), SchemaRef: "#/$defs/RealtimeTranslationServerEventSessionOutputAudioDelta"},
	{Profile: Profile("translation"), Direction: Direction("server"), Type: EventType("session.output_transcript.delta"), SchemaRef: "#/$defs/RealtimeTranslationServerEventSessionOutputTranscriptDelta"},
	{Profile: Profile("translation"), Direction: Direction("server"), Type: EventType("session.updated"), SchemaRef: "#/$defs/RealtimeTranslationServerEventSessionUpdated"},
}
